//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Encargadoes = new HashSet<Encargado>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public System.DateTime Fecha_de_Ingreso { get; set; }
        public System.DateTime Fecha_de_Egreso { get; set; }
        public bool Estado { get; set; }
        public string Telefono { get; set; }
        public string Cuil { get; set; }
        public int Id_Sucursal { get; set; }
    
        public virtual Sucursal Sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Encargado> Encargadoes { get; set; }

        public Empleado(int Id, string Nombre, string Apellido, DateTime Fecha_de_Ingreso, DateTime Fecha_de_Egreso, bool Estado, string Telefono, string Cuil, int Id_Sucursal)
        {
            this.Id = Id;
            this.Nombre = Nombre;
            this.Apellido = Apellido;
            this.Fecha_de_Ingreso = Fecha_de_Ingreso;
            this.Fecha_de_Egreso = Fecha_de_Egreso;
            this.Estado = Estado;
            this.Telefono = Telefono;
            this.Cuil = Cuil;
            this.Id_Sucursal = Id_Sucursal;
        }
    }
}
