//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encargado
    {
        public int id_encargado { get; set; }
        public int clave { get; set; }
        public int id_empleado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
