//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consola
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public int id_evento { get; set; }
        public int id_empleados { get; set; }
        public System.DateTime fecha_log { get; set; }
        public string cambio { get; set; }
    }
}
